export enum Role {
  CANDIDAT = 1,
  ENTREPRISE = 2,
  ADMIN = 7
}

export enum Statut {
  ETUDIANT = 0,
  STAGIAIRE = 1,
  SALARIE_CDD = 2,
  ALTERNANT = 3,
  SALARIE_CDI = 4,
  CHERCHEUR = 5,
  INDEPENDANT = 6,
  ONG = 7,
  STARTUP = 8,
  PME_PMI = 9,
  SARL = 10,
  GE = 11,
  PUBLIC = 12,
  AUTRE = 13
}

export enum Filiere {
  DROIT = 'droit',
  ECONOMIE = 'économie',
  SOCIOLOGIE = 'sociologie',
  MANAGEMENT = 'Administration',
  RH = 'rh',
  TELECOM = 5,
  MINE = 6,
  INFORMATIQUE = 7,
  MATHEMATIQUE = 8,
  BIOLOGIE = 9,
  AGRICULTURE = 10,
  BTP = 11,
  ARCHITECTURE = 12,
  DESIGN = 13,
  ART =,
  MUSIQUE = ,
  CULTURE = ,
  GEOLOGIE = ,
  METEO = ,
  JOURNALISME = ,
  COMMERCE = ,
  MARKETING = ,
  ENSEIGNEMENT = ,
  CHIMIE = ,
  MEDECINE = ,
  PHARMACIE = ,
  AERONAUTIQUE = ,
  MARITIME = ,
  SPACIALE = ,
  ELECTRONIQUE = ,
  MATERIAUX = ,
  INDUSTRIE = ,
}
