export enum Role {
  CANDIDAT = 1,
  ENTREPRISE = 2,
  ADMIN = 7
}

export enum Statut {
  ETUDIANT = 0,
  STAGIAIRE = 1,
  SALARIE_CDD = 2,
  ALTERNANT = 3,
  SALARIE_CDI = 4,
  CHERCHEUR = 5,
  INDEPENDANT = 6,
  ONG = 7,
  STARTUP = 8,
  PME_PMI = 9,
  SARL = 10,
  GE = 11,
  PUBLIC = 12,
  AUTRE = 13
}

export enum Filiere {
  ADMIN = 'administration',
  AERONAUTIQUE = 'aéronautique',
  AGRICULTURE = 'agriculture',
  ARCHITECTURE = 'architecture',
  ARMEE = 'arméé',
  ART = 'art',
  BIOLOGIE = 'biologie',
  BTP = 'batiment et travaux public',
  CHIMIE = 'chimie',
  COMMERCE = 'commerce',
  COMMUNICATION = 'communication',
  CULTURE = 'culture',
  DESIGN = 'design',
  DROIT = 'droit',
  ECONOMIE = 'économie',
  ELECTRONIQUE = 'électronique',
  ELEVAGE = 'élevage',
  ENSEIGNEMENT = 'enseignement',
  FINANCE = 'finance',
  GEOLOGIE = 'géologie',
  JOURNALISME = 'journalisme',
  HOTELLERIE = 'hotelerie',
  INDUSTRIE = 'industrie',
  INFORMATIQUE = 'informatique',
  MARITIME = 'maritime',
  MARKETING = 'marketing',
  MATERIAUX = 'matériaux',
  MATHEMATIQUE = 'mathématiques',
  MEDECINE = 'médecine',
  METEO = 'météorologie',
  MINE = 'mine',
  MUSIQUE = 'musique',
  PHARMACIE = 'pharmacie',
  RH = 'ressources humaines',
  SECURITE = 'sécurité',
  SOCIOLOGIE = 'sociologie',
  STATISTIQUES = 'statistiques',
  SPACIALE = 'spaciale',
  TELECOM = 'télécommunication',
  TRANSPORT = 'transport'
}
