export const Secteurs = [
  { name: 'informatiques' },
  { name: 'transports' },
  { name: 'btp' },
  { name: 'architecture' },
  { name: 'biochimie' },
  { name: 'mine' },
  { name: 'artisanat' },
  { name: 'tourisme' },
  { name: 'enseignement' },
  { name: 'finance' },
  { name: 'banque' },
  { name: 'assurance' },
  { name: 'droit' },
  { name: 'culture' },
  { name: 'industrie' },
  { name: 'telecommunication' },
  { name: 'energie' },
  { name: 'communication' },
  { name: 'aéronautique' },
  { name: 'maritime' },
  { name: 'pétrol' },
  { name: 'cinema' },
  { name: 'art' },
];
